# Generated by Django 3.2.8 on 2021-11-11 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20211101_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_image',
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fav_author',
            field=models.CharField(default='', max_length=255),
        ),
    ]
