# Generated by Django 3.2.8 on 2021-10-23 10:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photos', '0002_alter_photo_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='author',
            field=models.ForeignKey(default=None,null=True, blank=True, editable=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='photo',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 10, 23, 10, 16, 49, 726460, tzinfo=utc))
        ),
        migrations.AddField(
            model_name='photo',
            name='title',
            field=models.CharField(default='Photo Title', max_length=30),
        ),
    ]
