# Generated by Django 3.2.8 on 2021-11-12 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_alter_photo_title'),
        ('photos', '0005_alter_photo_title'),
    ]

    operations = [
    ]
