# Generated by Django 3.2.8 on 2021-11-13 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_merge_0002_alter_photo_title_0005_alter_photo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
