# Generated by Django 3.2.8 on 2021-11-13 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0008_alter_photo_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
