# Generated by Django 3.2.8 on 2021-11-13 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0010_alter_photo_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='date',
        ),
    ]
