# Generated by Django 3.2.8 on 2021-11-14 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0016_auto_20211113_2339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='email',
        ),
    ]
