# Generated by Django 3.2.8 on 2021-11-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0018_auto_20211114_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='body',
            field=models.TextField(default=False),
        ),
    ]
